version: '3.1'
services:
  stats-server:
    build: ./stats
    platform: 'linux/x86_64'
    container_name: stats-server
    restart: always
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statsdb
      - SPRING_DATASOURCE_USERNAME=statsuser
      - SPRING_DATASOURCE_PASSWORD=statsuser

  stats-db:
    image: postgres:14-alpine
    platform: 'linux/x86_64'
    container_name: stats-db
    ports:
      - "6544:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=statsdb
      - POSTGRES_USER=statsuser
      - POSTGRES_PASSWORD=statsuser

  ewm-service:
    build: ./ewm
    platform: 'linux/x86_64'
    container_name: ewm-service
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - ewm-db
    environment:
      - TZ="Europe/Moscow"
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewmdb
      - SPRING_DATASOURCE_USERNAME=ewmuser
      - SPRING_DATASOURCE_PASSWORD=ewmuser
      - STATS_SERVER_URL=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    platform: 'linux/x86_64'
    container_name: ewm-db
    ports:
      - "6546:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ewmdb
      - POSTGRES_USER=ewmuser
      - POSTGRES_PASSWORD=ewmuser